language: java
jdk: oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - mysql
  - docker

before_install:
  - wget https://github.com/jwilder/dockerize/releases/download/v0.2.0/dockerize-linux-amd64-v0.2.0.tar.gz
  - tar -xzvf dockerize-linux-amd64-v0.2.0.tar.gz
  - rm dockerize-linux-amd64-v0.2.0.tar.gz
  - ./dockerize -template docker/solrconfig.xml.tmpl:src/main/resources/solrconfig.xml
  - ./dockerize -template docker/log4j.xml.tmpl:src/main/resources/log4j.xml

before_script:
  - mysql -e 'create database search_test;'

script:
  - mvn clean test

after_success:
  - if [ "$TRAVIS_BRANCH" == "test" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    export REPO=datacite/search;
    docker build -f Dockerfile -t $REPO:$COMMIT .;
    docker push $REPO:$COMMIT;
    fi

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
