language: java
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2

services:
  - mysql

before_install:
  - wget https://github.com/jwilder/dockerize/releases/download/v0.2.0/dockerize-linux-amd64-v0.2.0.tar.gz
  - tar -xzvf dockerize-linux-amd64-v0.2.0.tar.gz
  - rm dockerize-linux-amd64-v0.2.0.tar.gz
  - ./dockerize -template docker/solrcore.properties.tmpl:solr_home/collection1/conf/solrcore.properties
  - ./dockerize -template docker/solrconfig.xml.tmpl:src/main/resources/solrconfig.xml
  - ./dockerize -template docker/log4j.xml.tmpl:src/main/resources/log4j.xml

before_script:
  - mysql -e 'create database search_test;'

script:
  - mvn clean test

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
