version: '2'

services:
  search:
    env_file: .env
    image: datacite/search:test
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/root/.m2
      - ~/efsmock:/data/solr/collection1
      # - ./docker:/home/app/docker
  db:
    env_file: .env
    image: mysql:5.6
    ports:
      - "3307:3306"
