version: '2'

services:
  search:
    env_file: .env
    image: datacite/search 
    ports:
      - "8080:8080"
      - "7776:7776"
    volumes:
      - ~/.m2:/root/.m2
  db:
    env_file: .env
    image: mysql:5.6
    ports:
      - "3307:3306"
