#!/bin/bash

function main {
  cmd=$1;shift
  fmt="wt=json&indent=true"
  case "$cmd" in
    "help" ) help;;
    "status" ) get "admin/cores?action=status&$fmt";echo;;
    "select" ) get "select?$1";;
    "query" ) get "select?q=$1&indent=true$2";;
    "count" ) get 'select?q=*:*&rows=0&indent=true';;
    "update" ) post 'update';;
    "commit" ) post 'update' '<commit/>';echo;;
    "optimize" ) post 'update' '<optimize/>';echo;;
    "purge" ) post 'update' '<delete><query>*:*</query></delete>';echo;;
    "import" )
      sub=$1;shift
      case "$sub" in
        "status" ) get "admin/dataimport?$fmt";echo;;
        "abort" ) get "admin/dataimport?command=abort&$fmt";echo;;
        "full" ) get "admin/dataimport?command=full-import&clean=true&commit=true&optimize=false&$fmt";echo;;
        "delta" ) get "admin/dataimport?command=full-import&clean=false&commit=true&optimize=false&$fmt";echo;;
        * )
          echo unknown command \"$cmd $sub\"
          help;;
      esac;;
    * )
      echo unknown command \"$cmd\"
      help;;
  esac
}

function post {
  check_env
  url=$SOLR_URL/$1
  echo $url 1>&2
  
  if [ -n "$SOLR_ADMIN" ]; then
    credentials="-u $SOLR_ADMIN:$SOLR_PASS"
  fi
  
  if [ -z "$2" ]; then
    curl -s $credentials -H "Content-Type: text/xml" --data-binary @- $url < /dev/stdin
  else
    curl -s $credentials -H "Content-Type: text/xml" --data-binary $2 $url
  fi

}

function get {
  check_env
  url=$SOLR_URL/$1
  echo $url 1>&2
  curl -s -u $SOLR_ADMIN:$SOLR_PASS $url
}

function check_env {
  if [ -z "$SOLR_URL" ]; then
    echo env var SOLR_URL is undefined 1>&2
    exit 1
  fi
}

function help {
  cat <<EOF
  
  solr-client - simple command client for interacting with solr
  
  usage:
  
  solr-client <command>
  
  commands:
  
    help                 - prints this help
    status               - solr status
    
    count                - get number of results for q=*:*
    select <params>      - generic select method (/select?<params>)
    query <q> [<params>] - simple query (/select?q=<q><params>)

    commit               - commit
    optimize             - optimize
    purge                - purge whole index
    update [<body>]      - generic update method (/update);
                             post <body> or read from stdin if <body> is missing

    import status        - status of DataImportHandler
    import full          - do full import
    import delta         - do delta import
    import abort         - abort data import
    
  environment variables:
  
    The following env var has to be set:
  
    SOLR_URL             - url of solr instance
    
    The following env vars are only required, if access is password secured 
    
    SOLR_ADMIN           - username to access admin realm
    SOLR_PASS            - password of admin user
    
EOF
}

main $@
